# callpeak.sub 
# HTCondor submit file with docker container for performing
# MACS2 callpeak on treatment and control bam files
# Run: condor_submit callpeak.sub

# Line added to ensure node has access to staging
Requirements = (Target.hasCHTCStaging == true)

# Provide HTCondor with the name of the Docker container
container_image = docker://jespina/chtc-callpeak:dev
universe = container

# Specify executable and arguments
# $treatment is the treatment bam filename
# $control is the control bam filename
# $setting specifies whether to use default narrowPeak call or broadPeak
executable = callpeak.sh
arguments = $(treatment) $(control) $(setting)
   		
# specify name of the log, standard error, and standard output files 
# $(Cluster) represents queue number assigned to this set of jobs at the time of submission
# $(Process) is integer number for each job starting from "0"
log = $(treatment)_callpeak_$(Cluster)_$(Process).log
error = $(treatment)_callpeak_$(Cluster)_$(Process).err
output = $(treatment)_callpeak_$(Cluster)_$(Process).out
   
# transfer files in/out of /home/{net-id}/
# transfer output files on exit from compute node
should_transfer_files = YES
transfer_input_files = 
when_to_transfer_output = ON_EXIT
   
# memory, disk, and cpu requirements
request_cpus = 4
request_memory = 24GB
request_disk = 20GB
   
# Tell HTCondor to queue over a samplesheet.txt file
queue treatment,control,setting from samplesheet.txt

###END
